name: CI

on:
  pull_request:
    
env:
  TEST_QUAY_USERNAME: sandyada   
    
jobs:    
  build-openstack-operator:
    name: Build openstack-operator image using buildah
    runs-on: ubuntu-latest

    steps: 
      - name: Checkout
        uses: actions/checkout@v3

      - run: ls -alr "$GITHUB_WORKSPACE/"



