name: CI

on:
  push:
    
env:
  TEST_QUAY_USERNAME: sandyada   
    
jobs:    
  build-openstack-operator:
    name: Build openstack-operator image using buildah
    runs-on: ubuntu-latest

    steps: 
      - name: Checkout
        uses: actions/checkout@v3
        with:
          repository: openstack-k8s-operators/openstack-operator
          path: openstack-operator
          
      - name: Print
        run: |
          echo dir is ${{ github.workspace }}
          echo "${GITHUB_WORKSPACE}"
          ls ${{ github.workspace }}
