name: CI

on:
  push:
    branches: [ "main" ]
    
env:
  TEST_QUAY_USERNAME: sandyada   
    
jobs:    
  build-openstack-operator:
    name: Build openstack-operator image using buildah
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        repository: openstack-k8s-operators/openstack-operator
        
    - name: Edit custom-bundle.Dockerfile
      run: |
        sed "s/quay.io\/openstack-k8s-operators\/keystone-operator-bundle:latest/quay.io\/${{ env.imagenamespace }}\/keystone-operator-bundle:test/" "${GITHUB_WORKSPACE}"/custom-bundle.Dockerfile
        cat "${GITHUB_WORKSPACE}"/custom-bundle.Dockerfile
    
