name: CI

on:
  pull_request:
    
env:
  TEST_QUAY_USERNAME: sandyada   
    
jobs:    
  build-openstack-operator:
    name: Build openstack-operator image using buildah
    runs-on: ubuntu-latest

    steps: 
      - name: Checkout
        uses: actions/checkout@v3

      - run: |
          echo ${{ github.sha }}
          echo ${{ github.event.pull_request.head.sha}} 
          echo ${{ github.event.pull_request.head.sha}}  > ${{ github.sha }}
          echo ${{ github.sha }} 
          
      - run: |
          echo ${{ github.sha }}



