name: CI

on:
  push:
    branches: [ "main" ]
    
env:
  TEST_QUAY_USERNAME: sandyada   
    
jobs:    
  build-openstack-operator:
    name: Build openstack-operator image using buildah
    runs-on: ubuntu-latest

    steps: 
      - name: Checkout
        uses: actions/checkout@v3
        with:
          path: main
          
      - uses: actions/checkout@v3
        with:
          repository: tripleo-ci/openstack-k8s-operators-ci
          ref: check_jobs
          path: openstack-k8s-operators-ci

      - run: ls -alr "$GITHUB_WORKSPACE/"



