name: CI

on:
  workflow_call:
    inputs:
      operator_name:
        required: true
        type: string
    secrets:
      IMAGENAMESPACE:
        required: true
      QUAY_USERNAME:
        required: true
      QUAY_PASSWORD:
        required: true

env:
  imageregistry: 'quay.io'
  imagenamespace: ${{ secrets.IMAGENAMESPACE || secrets.QUAY_USERNAME }}

jobs:
  check-secrets:
    runs-on: ubuntu-latest
    steps:
      - name: Check secrets are set
        id: have-secrets
        if: "${{ env.imagenamespace != '' }}"
        run: echo "::set-output name=ok::true"
    outputs:
      have-secrets: ${{ steps.have-secrets.outputs.ok }}

  build-operator:
    name: Build operator image using buildah
    runs-on: ubuntu-latest
    needs: [check-secrets]
    if: needs.check-secrets.outputs.have-secrets == 'true'

    steps:
    - uses: actions/checkout@v2

    - name: Get branch name
      id: branch-name
      uses: tj-actions/branch-names@v5

    - name: Buildah Action
      id: build-operator
      uses: redhat-actions/buildah-build@v2
      with:
        image: ${{ inputs.operator_name }}
        tags: ${{ github.sha }}
        containerfiles: |
          ./Dockerfile
          
    - name: Push operator To ${{ env.imageregistry }}
      uses: redhat-actions/push-to-registry@v2
      with:
        image: ${{ steps.build-operator.outputs.image }}
        tags: ${{ steps.build-operator.outputs.tags }}
        registry: ${{ env.imageregistry }}/${{ env.imagenamespace }}
        username: ${{ secrets.QUAY_USERNAME }}
        password: ${{ secrets.QUAY_PASSWORD }}

  build-operator-bundle:
    needs: [ check-secrets, build-operator ]
    name: ${{ inputs.operator_name }}-bundle
    runs-on: ubuntu-latest
    if: needs.check-secrets.outputs.have-secrets == 'true'

    steps:
    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.18.x

    - name: Checkout ${{ inputs.operator_name }} repository
      uses: actions/checkout@v2

    - name: Install operator-sdk
      uses: redhat-actions/openshift-tools-installer@v1
      with:
        source: github
        operator-sdk: '1.22.1'

    - name: Log in to Quay Registry
      uses: redhat-actions/podman-login@v1
      with:
        registry: ${{ env.imageregistry }}
        username: ${{ secrets.QUAY_USERNAME }}
        password: ${{ secrets.QUAY_PASSWORD }}

    - name: Create bundle image
      run: |
        pushd "${GITHUB_WORKSPACE}"/.github/
        chmod +x "create_bundle.sh"
        "./create_bundle.sh"
        popd
      env:
        REGISTRY:  ${{ env.imageregistry }}/${{ env.imagenamespace }}
        GITHUB_SHA: ${{ github.sha }}
        BASE_IMAGE: ${{ inputs.operator_name }}

    - name: Get branch name
      id: branch-name
      uses: tj-actions/branch-names@v5

    - name: Build ${{ inputs.operator_name }}-bundle using buildah
      id: build-operator-bundle
      uses: redhat-actions/buildah-build@v2
      with:
        image: ${{ inputs.operator_name }}-bundle
        tags: ${{ github.sha }}
        containerfiles: |
          ./bundle.Dockerfile
          
    - name: Push ${{ inputs.operator_name }} To ${{ env.imageregistry }}
      uses: redhat-actions/push-to-registry@v2
      with:
        image: ${{ steps.build-operator-bundle.outputs.image }}
        tags: ${{ steps.build-operator-bundle.outputs.tags }}
        registry:  ${{ env.imageregistry }}/${{ env.imagenamespace }}
        username: ${{ secrets.QUAY_USERNAME }}
        password: ${{ secrets.QUAY_PASSWORD }}

  build-operator-index:
    needs: [ check-secrets, build-operator-bundle ]
    name: ${{ inputs.operator_name }}-index
    runs-on: ubuntu-latest
    if: needs.check-secrets.outputs.have-secrets == 'true'

    steps:
    - name: Checkout ${{ inputs.operator_name }} repository
      uses: actions/checkout@v2

    - name: Get branch name
      id: branch-name
      uses: tj-actions/branch-names@v5

    - name: Install opm
      uses: redhat-actions/openshift-tools-installer@v1
      with:
        source: github
        opm: 'latest'

    - name: Log in to Red Hat Registry
      uses: redhat-actions/podman-login@v1
      with:
        registry: ${{ env.imageregistry }}
        username: ${{ secrets.QUAY_USERNAME }}
        password: ${{ secrets.QUAY_PASSWORD }}

    - name: Create index image
      run: |
        pushd "${GITHUB_WORKSPACE}"/.github/
        chmod +x "create_opm_index.sh"
        "./create_opm_index.sh"
        popd
      env:
        REGISTRY:  ${{ env.imageregistry }}/${{ env.imagenamespace }}
        GITHUB_SHA: ${{ github.sha }}
        BUNDLE_IMAGE: ${{ inputs.operator_name }}-bundle
        INDEX_IMAGE_TAG: ${{ github.sha }}
        INDEX_IMAGE: ${{ inputs.operator_name }}-index

    - name: Push ${{ inputs.operator_name }}-index To ${{ env.imageregistry }}
      uses: redhat-actions/push-to-registry@v2
      with:
        image: ${{ inputs.operator_name }}-index
        tags: ${{ github.sha }}
        registry:  ${{ env.imageregistry }}/${{ env.imagenamespace }}
        username: ${{ secrets.QUAY_USERNAME }}
        password: ${{ secrets.QUAY_PASSWORD }}
