name: CI

on:
  push:
    
env:
  TEST_QUAY_USERNAME: sandyada   
    
jobs:    
  build-openstack-operator:
    name: Build openstack-operator image using buildah
    runs-on: ubuntu-latest

    steps:
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.18    
      - name: Print
        run: |
          go version
